src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('tests/', include('testify.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, TestListView, TestView, TestStartView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:test_id>/question/<int:order_number>', QuestionView.as_view(), name='question'),
    path('<int:id>/', TestView.as_view(), name='details'),
    path('<int:test_id>/start/', TestStartView.as_view(command='start'), name='start'),
    # path('<test_id>/next/', TestRunView.as_view(command='next'), name='next'),
    # path('<test_id>/finish/', TestRunView.as_view(command='finish'), name='finish'),
    # path('<test_id>/run/', TestRunnerView.as_view(), name='run'),
]

src/testify/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from accounts.models import User
from core.models import BaseModel


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.name}'


class Test(models.Model):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    @property
    def questions_count(self):
        return self.questions.count()

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Answer(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='answers', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class TestResult(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='test_results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='test_results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)

    score = models.DecimalField(default=0.0, decimal_places=2, max_digits=5,
                                validators=[MinValueValidator(0), MaxValueValidator(100)])

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(Question.ANSWER_MAX_LIMIT)]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(Question.ANSWER_MAX_LIMIT)]
    )
    points_achieved = models.SmallIntegerField(default=0)
    used_time = models.CharField(max_length=64, null=True, blank=True)

    def __str__(self):
        return f'{self.test} ran by {self.user.full_name()} at {self.write_date}'

    def time_spent(self):
        return self.write_date - self.create_date

    @staticmethod
    def best_result(test_id):
        queryset = TestResult.objects.filter(test=test_id)
        if queryset.count() > 0:
            obj = queryset.extra(select={
                'points': 'num_correct_answers - num_incorrect_answers', 'duration': 'write_date - create_date'},
                order_by=['-points', 'duration'])[0]
            result = f'{obj.user} scored {obj.num_correct_answers} points'
            return result
        else:
            result = 'No one has done this test yet'
            return result

    @staticmethod
    def last_run(test_id):
        if TestResult.objects.filter(test=test_id).count() > 0:
            ob = TestResult.objects.filter(test=test_id).order_by('-write_date').first()
            result = ob.write_date
            return result
        else:
            result = 'No one has run this test yet'
            return result

src/testify/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, ModelForm, modelformset_factory

from testify.models import Answer, Question


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

    def clean(self):
        pass


class AnswerForm(ModelForm):
    is_selected = forms.BooleanField()
    # test = fields.CharField()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['text'].label = ""
        self.fields['is_selected'].label = ""

    class Meta:
        model = Answer
        fields = ['is_selected', 'text']
        widgets = {
            'text': forms.TextInput(attrs={'readonly': True})
        }


AnswerFormSet = modelformset_factory(
    model=Answer,
    form=AnswerForm,
    extra=0
)


class QuestionsInlineFormSet(BaseInlineFormSet):

    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError('Quantity of questions is out of range ({}..{})'.format(
                self.instance.QUESTION_MIN_LIMIT, self.instance.QUESTION_MAX_LIMIT
            ))


class AnswerInlineFormSet(BaseInlineFormSet):

    def clean(self):
        if not (self.instance.ANSWER_MIN_LIMIT <= len(self.forms) <= self.instance.ANSWER_MAX_LIMIT):
            raise ValidationError('Quantity of answers is out of range ({}..{})'.format(
                self.instance.ANSWER_MIN_LIMIT, self.instance.ANSWER_MAX_LIMIT
            ))

        num_correct_answers = sum([
            1
            for form in self.forms
            if form.cleaned_data['is_correct']
        ])

        if num_correct_answers == 0:
            raise ValidationError('At LEAST one answer must be correct!')

        if num_correct_answers == len(self.forms):
            raise ValidationError('Not allowed to select ALL answers!')

src/testify/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

from accounts.models import User
from testify.forms import AnswerFormSet
from testify.models import Question, Test, TestResult
from decimal import Decimal


class QuestionView(View):

    def get(self, request, test_id, order_number):
        question = Question.objects.get(test__id=test_id, order_number=order_number)
        answers = question.answers.all()
        form_set = AnswerFormSet(queryset=answers)

        return render(
            request=request,
            template_name='question.html',
            context={
                'question': question,
                'form_set': form_set,
            }
        )

    def post(self, request, test_id, order_number):
        question = Question.objects.get(test__id=test_id, order_number=order_number)
        test = question.test
        answers = question.answers.all()
        form_set = AnswerFormSet(data=request.POST)
        possible_choices = len(form_set.forms)
        selected_choices = [
            # form.cleaned_data.get('is_selected', False)
            'is_selected' in form.changed_data
            for form in form_set.forms
        ]

        num_selected_choices = sum(selected_choices)

        if num_selected_choices == 0:
            messages.error(self.request, extra_tags='danger', message="ERROR: You should select at least 1 answer!")
            return redirect(reverse('tests:question', args=(test_id, order_number)))

        if num_selected_choices == possible_choices:
            messages.error(self.request, extra_tags='danger', message="ERROR: You can't select ALL answer!")
            return redirect(reverse('tests:question', args=(test_id, order_number)))

        correct_choices = sum(
            answer.is_correct == choice
            for answer, choice in zip(answers, selected_choices)
        )

        point = int(correct_choices == possible_choices)
        point_weighted = question.test.questions.count() - correct_choices

        if point_weighted < 0:
            point_weighted = 0

        current_test = request.session['current_test']
        current_test['num_correct_answers'] += point
        current_test['num_incorrect_answers'] += (1 - point)

        if order_number == question.test.questions.count():
            user = User.objects.get(username=request.user)
            current_rating = user.rating
            new_rating = current_rating + Decimal(point_weighted)
            current_test['points_achieved'] = new_rating
            user.rating = new_rating
            user.save()

        if order_number == question.test.questions_count:
            test_result = TestResult.objects.create(
                user=request.user,
                state=TestResult.STATE.FINISHED,
                test=test,
                num_correct_answers=current_test['num_correct_answers'],
                num_incorrect_answers=current_test['num_incorrect_answers'],
            )
            return render(
                request=request,
                template_name='finish.html',
                context={
                    'test_result': test_result,
                    'time_spent': test_result.write_date - test_result.create_date,
                    'test_result_score': test_result.num_correct_answers/test.questions_count
                }
            )
        else:
            return redirect(reverse('tests:question', args=(test_id, order_number+1)))


class TestView(DetailView):
    model = Test
    template_name = 'details.html'
    context_object_name = 'test'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        all_results = TestResult.objects.filter(test=self.kwargs['id'])
        context['all_results'] = all_results
        context['best_result'] = TestResult.best_result(test_id=self.kwargs['id'])
        context['last_run'] = TestResult.last_run(test_id=self.kwargs['id'])
        return context


class TestStartView(View):
    command = None

    def get(self, request, test_id):
        if 'current_test' not in request.session:
            context = {
                'test_id': test_id,
                'order_number': 1,
                'num_correct_answers': 0,
                'num_incorrect_answers': 0
            }
            request.session['current_test'] = context

        context = request.session['current_test']

        order_number = context['order_number']

        return redirect(reverse('tests:question', args=(test_id, order_number)))


class TestListView(ListView):
    model = Test
    template_name = 'list.html'
    context_object_name = 'tests'

src/testify/templates/details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    {{ test }}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Test info</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Description</td>
                        <td>{{ test.description }}</td>
                      </tr>
                      <tr>
                        <td>Num of questions</td>
                        <td>{{ test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Num of runs</td>
                        <td>{{ test.test_results.count }}</td>
                      </tr>
                      <tr>
                        <td>Best result</td>
                        <td>{{ best_result }}</td>
                      </tr>
                      <tr>
                        <td>Last run</td>
                        <td>{{ last_run }}</td>
                      </tr>
                      <tr>
                        <td>Current open run</td>
                        <td>N/A</td>
                      </tr>
                    </tbody>
                  </table>
            </div>

            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{{ test.image.url }}">
                </div>

                <div class="d-flex justify-content-center mt-5 mb-5" >
                        <a href="{% url 'tests:start' test_id=test.id %}" type="button" class="btn-lg btn-success">START ▶️</a>
                </div>
{#                {% if test_result.is_new %}#}
{#                    <div class="d-flex justify-content-center mt-5 mb-5" >#}
{#                        <a href="{% url 'test:next' pk=test.id %}" type="button" class="btn-lg btn-success">START ▶️</a>#}
{#                    </div>#}
{#                {% else %}#}
{#                    <div class="d-flex justify-content-center mt-5 mb-5" >#}
{#                        <a href="{% url 'test:next' pk=test.id %}" type="button" class="btn-lg btn-warning">CONTINUE ▶️</a>#}
{#                    </div>#}
{#                {% endif %}#}
            </div>
        </div>
    </div>

    <table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>User</th>
            <th>Started</th>
            <th>Time spent</th>
            <th>Points</th>
        </tr>
    {% for result in all_results %}
        <tr>
            <td>{{ result.id }}</td>
            <td>{{ result.user }}</td>
            <td>{{ result.write_date }}</td>
            <td>{{ result.time_spent }}</td>
            <td>{{ result.points_achieved }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

src/testify/templates/finish.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>{{ test_result.test.title }}</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Correct answers</td>
                        <td>{{ test_result.num_correct_answers }} / {{ test_result.test.questions_count }}</td>
                      </tr>
                      <tr>
                        <td>Score</td>
                        <td>{{ test_result_score|floatformat:2 }}</td>
                      </tr>
                      <tr>
                        <td>Time spent</td>
                        <td>{{ time_spent }}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{% static 'common/finish.jpg' %}">
                </div>

                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a href="{% url 'tests:list' %}" type="button" class="btn-lg btn-success">START ANOTHER TEST ▶️</a>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

src/testify/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    Test list
{% endblock %}

{% block content %}
    {% if tests %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Level</th>
                  <th></th>
                </tr>
            </thead>

            {% for test in tests %}
                <tr>
                    <td><img class="rounded-circle p-1 m-1" width="150" height="150"  src="{{ test.image.url }}"></td>
                    <td> {{ test.title }}</td>
                    <td> {{ test.description }}</td>
                    <td>
                            <img class="p-1 m-1" width="140" height="38" src="{% static 'common/level_'%}{{ test.get_level_display }}.png">
                    </td>

{#                    <td> <img src="{% static 'common/level_.png' %}" height="30px" width="40px"/> </td>#}
                    <td> <a href="{% url 'tests:details' test.id %}">DETAILS</a></td>
                </tr>
            {% endfor %}
        </table>

    {% else %}
        <p>No tests yet :(</p>
    {% endif %}
{% endblock %}

src/testify/templates/question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    Question #{{ question.order_number }}/{{ question.test.questions_count }}: <b>{{ question.text }}</b> ?
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        Possible answers:

        {{form_set.management_form}}

        {% for form in form_set %}
{#            <div class="checkbox">#}
{#              <label><input type="checkbox" name="{{ prefix }}{{ forloop.counter }}" value="1">   {{ answer }}</label>#}
{#            </div>#}
{#            {{ form.as_p }}#}
            <div class="mt-1">
{#                {{ form.is_selected }} <label for="{{ form.text.id_for_label }}">  {{ form.text.value }}</label>#}
                {{ form.is_selected }} <label>  {{ form.text.value }}</label>
            </div>

        {% endfor %}

        <div class="mt-3">
            <button type="submit" class="btn btn-success">Submit</button>

        </div>
    </form>
{% endblock %}

src/testify/templates/tests_list.html
{% extends 'base.html' %}

{% block header %}
    Test list
{% endblock %}

{% block content %}
    {% if tests %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Level</th>
                  <th></th>
                </tr>
            </thead>

            {% for test in tests %}
                <tr>
                    <td><img class="rounded-circle p-1 m-1" width="150" height="150"  src="{{ test.image.url }}"></td>
                    <td> {{ test.title }}</td>
                    <td> {{ test.description }}</td>
                    <td> {{ test.level }}</td>
{#                    <td> <img src="{% static 'common/level_.png' %}" height="30px" width="40px"/> </td>#}
                    <td> <a href="{% url 'tests:details' test.id %}">DETAILS</a></td>
                </tr>
            {% endfor %}
        </table>

    {% else %}
        <p>No tests yet :(</p>
    {% endif %}

{% endblock %}