src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountUpdateView,
    AccountListView,
    LeaderboardListView,
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('leaderboard/', LeaderboardListView.as_view(), name='leaderboard'),
    path('', AccountListView.as_view(), name='users'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('tests/', include('testify.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.urls import path

from core.views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, TestListView, TestView, TestStartView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:test_id>/question/<int:order_number>', QuestionView.as_view(), name='question'),
    path('<int:id>/', TestView.as_view(), name='details'),
    path('<int:test_id>/start/', TestStartView.as_view(command='start'), name='start'),
    # path('<test_id>/next/', TestRunView.as_view(command='next'), name='next'),
    # path('<test_id>/finish/', TestRunView.as_view(command='finish'), name='finish'),
    # path('<test_id>/run/', TestRunnerView.as_view(), name='run'),
]

src/accounts/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    rating = models.DecimalField(default=0.0, decimal_places=2, max_digits=5, validators=[MinValueValidator(0),
                                                                                          MaxValueValidator(100)])
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block title %}
        <title>Testify</title>
{% endblock %}
</head>
<body>

{%url 'tests:list' as tests_list %}
{%url 'accounts:leaderboard' as leaderboard_page %}
{%url 'accounts:users' as user_list %}
{%url 'accounts:profile' as profile_page %}
{%url 'accounts:register' as registration_page %}
{%url 'accounts:login' as login_page %}


<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold ">
  <div class="container">

  <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'tests:list' %}">Tests<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'core:index' %}">Leaderboard</a>
      </li>
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#      </li>#}
    </ul>

    <ul class="navbar-nav ">

            {%  if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>
               <li class="nav-item {% if request.path == tests_list %} active {% endif %}">
                    <a class="nav-link" href="{% url 'tests:list' %}">Tests</a>
                </li>
                <li class="nav-item {% if request.path == leaderboard_page %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:leaderboard' %}">Leaderboard</a>
                </li>

                <li class="nav-item {% if request.path == user_list %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:users' %}">Users</a>
                </li>

            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
            {% endif %}

    </ul>

  </div>
  </div>
</nav>

<div class="container">
{#            {% block header %}#}
{#                <h1>#}
{#                Welcome to LMS!#}
{#                </h1>#}
{#            {% endblock%}#}
{##}

    {% include 'includes/messages.html' %}

    <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
        {% block header %}
            <h1>
                Welcome to Testify!
            </h1>
        {% endblock %}
    </div>

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

src/templates/pagination.html
<nav aria-label="Navigator>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <li class="page-link" >
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last</a></li>
        {% endif %}
    </ul>
</nav>